
sudo: required
env:
    global:
        - SHA=$(git rev-parse --short HEAD)
        - CLOUDSDK_CORE_DISABLE_PROMPTS=1
services:
    - docker

before_install:
    # Build Docker image to test the app
    - docker image build -t crileroro/fe-shopping-react-tst:latest -f frontend/Dockerfile.dev ./frontend/fe-shopping

script:
    - docker container run -e CI=true crileroro/fe-shopping-react-tst:latest npm run test -- --coverage

after_success:
    # Login to Docker Hub
    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
    - docker image build -t crileroro/be-shopping-python-prd:aws_alb -f backend/Dockerfile.dev ./backend
    - docker image build -t crileroro/fe-shopping-react-prd:aws_alb -f frontend/Dockerfile ./frontend
    - docker push crileroro/be-shopping-python-prd:aws_alb_v1
    - docker push crileroro/fe-shopping-react-prd:aws_alb_v1
