
sudo: required
env:
    global:
        - SHA=$(git rev-parse --short HEAD)
services:
    - docker

before_install:
    - docker image build -t crileroro/fe-shopping-react -f frontend/Dockerfile.dev ./frontend/fe-shopping

script:
    - docker container run -e CI=true crileroro/fe-shopping-react npm run test -- --coverage

after_success:
    - docker image build -t crileroro/be-shopping-python-prd:"$SHA" -t crileroro/be-shopping-python-prd:latest -f backend/Dockerfile.dev ./backend
    - docker image build -t crileroro/fe-shopping-react-prd:"$SHA" -t crileroro/fe-shopping-react-prd:latest -f frontend/Dockerfile ./frontend
    
    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
    - docker push crileroro/be-shopping-python-prd:$SHA
    - docker push crileroro/fe-shopping-react-prd:$SHA

    - docker push crileroro/be-shopping-python-prd:latest
    - docker push crileroro/fe-shopping-react-prd:latest