apiVersion: apps/v1
kind: Deployment
metadata:
    name: be-deploy
    labels:
        tier: python_backend
spec:
    replicas: 2
    selector:
        matchLabels:
            run: python_backend
    template:
        metadata:
            name: pod-python-be
            labels:
                run: python_backend
        spec:
            containers:
                - name: be-shopping
                  image: crileroro/be-shopping-python-prd
                  ports:
                    - containerPort: 5000
                  envFrom:
                    - configMapRef:
                        name: be-env-variables
    