apiVersion: apps/v1
kind: Deployment
metadata:
    name: be-deploy
    labels:
        tier: python_backend
spec:
    replicas: 3
    selector:
        matchLabels:
            tier: python_backend
    template:
        metadata:
            name: pod-react-fe
            labels:
                tier: python_backend
        spec:
            containers:
                - name: be-shopping
                  image: crileroro/be-shopping-python:ca9cc67
                  ports:
                    - containerPort: 5000
                  env:
                    - name: HOST
                      value: '0.0.0.0'
                    - name: PORT
                      value: '5000'
                    - name: DEBUG
                      value: 'True'
    