apiVersion: v1
kind: Service
metadata:
    name: {{ .Values.serviceBackend.name }}
spec:
    type: ClusterIP
    selector:
        run: python_backend
    ports:
        - port: {{ .Values.backend.port }}
          targetPort: {{ .Values.backend.port }}
