apiVersion: v1
kind: Service
metadata:
    name: {{ .Values.serviceFrontend.name }}
spec:
    type: ClusterIP
    selector:
        run: react_frontend
    ports:
        - port: {{ .Values.frontend.port }}
          targetPort: {{ .Values.frontend.port }}